# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

variables:
  WORKING_DIR: 'src/ddo_transform'
  PACKAGE_MAJOR_VERSION:  1
  PACKAGE_MINOR_VERSION:  1
  PACKAGE_PATCH_VERSION:  $(Build.BuildId)

stages:
- stage: 'validate_pr'
  displayName: 'Validate PR'
  condition: and(always(), eq(variables['Build.Reason'], 'PullRequest')
  jobs:
  - job: 'validate_python_packages'
    displayName: 'Validate Python Packages'
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'

    - script: pip install -r requirements_dev.txt && pip install -r requirements.txt
      workingDirectory: $(WORKING_DIR)
      displayName: 'Install requirements'

    - script: make lint && make tests 
      workingDirectory: $(WORKING_DIR)
      displayName: 'Run lint tests'

    - script: make test && make lint
      workingDirectory: $(WORKING_DIR)
      displayName: 'Run lint tests'

- stage: 'publish_artifacts'
  displayName: 'Publish Build Artifacts'
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: 'publish_python_packages'
    displayName: 'Publish Python Packages'
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'

    - script: pip install -r requirements_dev.txt && pip install -r requirements.txt
      workingDirectory: $(WORKING_DIR)
      displayName: 'Install requirements'

    - script: make dist
      env:
        package_version: $(PACKAGE_MAJOR_VERSION).$(PACKAGE_MINOR_VERSION).$(PACKAGE_PATCH_VERSION)
      workingDirectory: $(WORKING_DIR)
      displayName: 'Create wheel package'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(WORKING_DIR)/dist'
        ArtifactName: 'dist'
      displayName: 'Publish Dist Artifacts'

  - job: 'publish_static_artifacts'
    displayName: 'Publish Static Artifacts'
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'databricks'
        ArtifactName: 'databricks'
      displayName: 'Publish Databricks Artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'adf/_scripts/deploymentadf.ps1'
        ArtifactName: 'adf_scripts'
      displayName: 'Publish ADF Scripts'